### ISSUE TITLE
timestamp in photo inspector is 4hrs earlier. I am in eastern time zone 

### ISSUE THREAD

**Issue by mbhstpete** [microsoft/photo-inspector#1]

**Comment by ltomuta** [comment]
The problem seems to be at https://github.com/nokia-developer/photo-inspector/blob/master/PhotoInspectorWP81/MagnifierApp/Pages/InfoPageViewModel.cs#L129 

EXIF's DateTimeOriginal seems to be in local time already, so that call to ToLocalTime() is not needed.
